Core/Community/contributors.md
README.md

minor changes. merging immediately.

clarify contributors, add links to readme.

---

index.html

This just adds a simple index.html page to serve as the beginning of making a GitHub page website for this project.
Right now it just has a very simple header made using Bootstrap. I'll be adding more as we go and I learn more about how GH Pages works.

Add index.html for GitHub pages

---

Core/Tools/Web/pages/about.html
Core/Tools/Web/pages/donate.html
Core/Tools/Web/pages/faq.html
Core/Tools/Web/pages/models.html

Adds a few temporary pages for the website. These are all linked to in the header.
@MattHJensen, can you change the settings so that the GH page is active for this repo so we can see if it works as expected? Everything works locally, but I'm not sure how GH pages will handle it. Instructions can be found [here](https://pages.github.com).

Add placeholder pages

---

index.html

Realized I never included a path to the other pages from the index page. Added them here so everything will work correctly.

Add paths to index page

---

Catalog/README.md
Community/contribute.md
Community/contributors.md
Community/roadmap.md
Criteria/library_criteria.md
README.md
RELEASES.md
Tests/README.md
Tools/Catalog-Builder/README.md

@andersonfrailey or @hdoupe, could you take a look and merge?

PSL-Core -> PSL

---

Community/contribute.md
Tools/Page-Builder/content/about.md
Tools/Page-Builder/content/contributemodel.md
Tools/Page-Builder/page_builder/pages.json
Tools/Web/pages/about.html
Tools/Web/pages/contribute-a-model.html
Tools/Web/pages/contribute.html
Tools/Web/pages/criteria.html
index.html

This PR adds information on contributing to PSL and updates some dead links accordingly. I'd appreciate a review of the contributing information I've added and am open to changing it how y'all see fit.
@MattHJensen @hdoupe @Peter-Metz

Add information on contributing

---

Tools/Web/pages/projects/B-Tax.html

The B-Tax model page was created using the models template from before @MattHJensen updated the nav bar at the top. This PR simply updates that page so that it matches all the others.

Update B-Tax Page

---

index.html

https://github.com/open-source-economics/PSL/issues/30#issuecomment-434845472

add context to PSL home page

---

Catalog/catalog.json
Catalog/index.html
Tools/Catalog-Builder/catalog_builder/catalog.py

This PR sorts the projects alphabetically by their name. In the future, it may be desirable to categorize the projects in the catalog.
cc @andersonfrailey

Sort projects alphabetically by repo name

---

about.html
index.html
news.html

I use text from contribute.md, about.md, and news.md to fill in the blurbs on the home page.

update home page blurbs

---

Criteria/library_criteria.md

Resolves #71. Thanks very much @martinholmer. 
cc @hdoupe

resolve 71 per Martin Holmer's suggestion

---

Catalog/Tax-Calculator.html
Catalog/catalog.json
Catalog/index.html

update Tax-Calculator card

---

Tools/Catalog-Builder/catalog_builder/catalog.py

Thanks for the bug report @Peter-Metz.

Fix argument to CatalogBuilder

---

Catalog/index.html
Tools/Catalog-Builder/templates/catalog_template.html

`Catalog-Builder/templates/catalog_template.html` was pointing to the wrong css style sheet

Fix catalog css

---

Newsletter/raw/Mar_Newsletter.html

This PR adds the html for a draft of the March newsletter (PDF attached). I plan to send the newsletter to our subscribers on Monday, so please post in this thread if you have any edits or additions to the newsletter before then. 
[PSL March Newsletter.pdf](https://github.com/PSLmodels/PSL/files/2947347/PSL.March.Newsletter.pdf)
cc: @MattHJensen @martinholmer @hdoupe @rickecon @jdebacker

Draft PSL March newsletter

---

Catalog/B-Tax.html
Catalog/Behavioral-Responses.html
Catalog/OG-USA.html
Catalog/ParamTools.html
Catalog/Tax-Calculator.html
Catalog/catalog.json
Catalog/index.html
Newsletter/March.html
Tools/Catalog-Builder/templates/card_template.html
Tools/Catalog-Builder/templates/catalog_template.html
Tools/Page-Builder/page_builder/pages.json
Tools/Page-Builder/templates/index_template.html
Tools/Page-Builder/templates/newsletter_template.html
Tools/Page-Builder/templates/page_template.html
about.html
index.html
news.html

Run `page-builder` to add March newsletter to newsletter page

Add March newsletter

---

CSS/page.css

This PR addresses the issues raised by @andersonfrailey in #104. Mainly, it changes the margins and Twitter sidebar from absolute to percentage terms 
cc: @hdoupe

Adjust margins of site pages

---

Catalog/B-Tax.html
Catalog/Behavioral-Responses.html
Catalog/OG-USA.html
Catalog/ParamTools.html
Catalog/Tax-Calculator.html
Catalog/index.html
Tools/Catalog-Builder/templates/card_template.html
Tools/Catalog-Builder/templates/catalog_template.html

Updates nav bar to direct to newsletter page with archive sidebar

Update nav bar links for catalog

---

index.html

Tweets were not centered on mobile.

Adjust website margins for Tweets

---

Newsletter/raw/May19_Newsletter.html
Tools/Page-Builder/page_builder/pages.json

This PR adds the May PSL newsletter to pslmodels.org. Please comment in this thread by tomorrow at noon if you have any edits or additions to the newsletter.
[May PSL Newsletter.pdf](https://github.com/PSLmodels/PSL-Infrastructure/files/3178263/May.PSL.Newsletter.pdf)
@MattHJensen @hdoupe @andersonfrailey @rickecon @jdebacker @martinholmer

Draft May PSL Newsletter

---

Newsletter/archive.html
Newsletter/raw/Jun19_Newsletter.html
Tools/Page-Builder/page_builder/pages.json

This PR adds a draft of the June PSL newsletter. Note the new "User Highlights" box at the top of the newsletter. If you have any additions or edits, please leave a note in this PR by tomorrow evening.
@MattHJensen @hdoupe @andersonfrailey @rickecon @martinholmer @jdebacker
[June PSL Newsletter.pdf](https://github.com/PSLmodels/PSL-Infrastructure/files/3330091/June.PSL.Newsletter.pdf)

June newsletter draft

---

events.html

Updates featured event on website to display July 31 CBO event

Update featured event on website

---

Newsletter/archive.html
Newsletter/raw/Jul19_Newsletter.html
Tools/Page-Builder/page_builder/pages.json

This PR adds the July PSL newsletter to pslmodels.org. You can check it out in the attached PDF. I'll send it out to our subscribers tomorrow afternoon, so please let me know if you have any changes before then. 
[PSL July Newsletter.pdf](https://github.com/PSLmodels/PSL-Infrastructure/files/3446972/PSL.July.Newsletter.pdf)

July newsletter draft

---

Tools/Page-Builder/templates/events_template.html
events.html

Lists August calls on events page

Update events page

---

about.html

@Peter-Metz, could you look over this?

Simplify About pg with pslmodels.org users in mind

---

Newsletter/archive.html
Newsletter/raw/Aug19_Newsletter.html

This PR adds the August PSL newsletter to the website.
Thanks everyone for sending me your updates. Feel free to review the newsletter draft (attached 
[here as PDF](https://github.com/PSLmodels/PSL-Infrastructure/files/3551501/August.PSL.Newsletter.pdf)) and comment here by noon on Friday if you have any edits or additions. Also, let me know if you think I have left something out of the "User Highlights" section.
cc: @MattHJensen @rickecon @jdebacker @martinholmer @andersonfrailey @hdoupe

August newsletter draft

---

Catalog/index.html
Newsletter/archive.html
about.html
events.html
index.html

Also changes "About PSL" -> "About" on navbar.

Add Discourse channel to navbar as "Forum"

---

Newsletter/archive.html
Newsletter/raw/Sept19_Newsletter.html

This PR adds the September newsletter to the site. Feel free to take a look at the Emporter link below and let me know if you have any edits by Monday morning.
https://6dee1f.emporter.app/Newsletter/raw/sept19_newsletter.html
cc: @MattHJensen @hdoupe @andersonfrailey @rickecon @jdebacker @martinholmer

September newsletter draft

---

CSS/page.css
Newsletter/archive.html
index.html

This PR modifies the newsletter archive and uses Bootstrap to clean it up.
Emporter: https://dddcb6.emporter.app/Newsletter/archive.html

Improved newsletter archive on site

---

Newsletter/archive.html
Newsletter/raw/Oct19_Newsletter.html

This PR adds the October newsletter to the site. I'll send the newsletter to our subscribers on Monday morning so feel free to suggest any additions or edits before then. PDF attached 
[here](https://github.com/PSLmodels/PSL-Infrastructure/files/3804320/October.PSL.Newsletter.pdf).
@MattHJensen @hdoupe @andersonfrailey @rickecon @jdebacker @martinholmer

October PSL Newsletter

---

Newsletter/archive.html
Newsletter/raw/Nov19_Newsletter.html

This PR adds the November newsletter to the PSL website.
If you have any edits or additions to the [attached draft](https://github.com/PSLmodels/PSL-Infrastructure/files/3912426/November.PSL.Newsletter.pdf), please comment here by tomorrow (12/3) afternoon.
@MattHJensen @hdoupe @andersonfrailey @jdebacker @ctszkin @towashington @rickecon

November PSL newsletter

---

Newsletter/archive.html
Newsletter/raw/Jan20_Newsletter.html

This PR adds the January newsletter to the PSL site.
Here's a [draft PDF](https://github.com/PSLmodels/PSL-Infrastructure/files/4119614/January.2020.PSL.Newsletter.pdf) for review - please respond here if you have any edits or additions by Wednesday afternoon.
@MattHJensen @hdoupe @rickecon @andersonfrailey @jdebacker @towashington

January 2020 newsletter

---

events.html

Jason and Matt are discussing and demo'ing the new OG-USA web application on Thursday (4/16) at 2p ET.
The webinar will be streamed at: https://www.aei.org/events/webinar-the-policy-simulation-library-dc-meeting-dynamic-tax-modeling-with-the-new-og-usa-web-application/

Update featured event on events page

---

Newsletter/archive.html
Newsletter/raw/May20_Newsletter.html
events.html

I'll plan on sending the newsletter out on Monday 6/1. Feel free to take a look at [the draft](https://htmlpreview.github.io/?https://github.com/Peter-Metz/PSL-Core/blob/june_updates/Newsletter/archive.html) and comment if you have any edits.

June website updates -- May newsletter and June calls

---

Newsletter/archive.html
Newsletter/raw/Jun20_Newsletter.html
events.html

Adds the June newsletter to the newsletter page and the July calls to the events page. I'll plan to send the newsletter out on Thursday July 2. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/Peter-Metz/PSL-Core/blob/july-updates/Newsletter/archive.html

Add June newsletter and July calls

---

Catalog/index.html
Tools/Catalog-Builder/templates/catalog_template.html

Updates `catalog_template.html` (the template used for automated PSL Catalog builds) to include links to the Initiatives and Donate pages.

Update navbar of catalog_template.html

---

initiatives.html

This PR adds descriptions of current PSL fundraising initiatives to the initiatives page.
cc @rickecon @donboyd5 @MattHJensen @Peter-Metz

Add details on current initiatives

---

Community/roadmap.md

This PR updates the community roadmap, following discussion from #181. Additions and edits are welcomed. I'll leave this open for a few days.
cc @MattHJensen @jdebacker @rickecon @hdoupe @andersonfrailey @chusloj @MaxGhenis @towashington

Community roadmap

---

Newsletter/archive.html
Newsletter/raw/Jul20_Newsletter.html

To add the **July 2020** PSL newsletter to the newsletter page. I'll plan to send the newsletter out on **Thursday, August 13**. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Jul20_Newsletter.html

To add July 2020 PSL newsletter

---

Newsletter/archive.html
Newsletter/raw/Aug20_Newsletter.html

To add the August 2020 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on **Monday, August 24**. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Aug20_Newsletter.html

Aug 2020 newsletter draft

---

Catalog/register.json

See https://github.com/MaxGhenis/microdf/issues/13.
All "MUST" requirements have been met except moving it into the PSLmodels organization. @MattHJensen if you can give me permission to add repos to PSLmodels I can transfer it.

Add microdf to PSL catalog register.json

---

Community/council.md

@MaxGhenis, is mghenis@gmail.com a good email for you?

Add max ghenis to leadership council (microdf)

---

Newsletter/archive.html
Newsletter/raw/Sep20_Newsletter.html

To add the September 2020 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on Friday, September 25. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Sep20_Newsletter.html

Sep 2020 newsletter draft

---

events.html

This PR adds two October (12, 26) developer meeting links to the events calendar.

Added October OG-USA dev meetings to events.html

---

Newsletter/archive.html
Newsletter/raw/Oct20_Newsletter.html

To add the **Oct 2020** PSL newsletter to the newsletter page. I'll plan to send the newsletter out on **Tuesday, Oct 27**. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Oct20_Newsletter.html

Oct 2020 newsletter draft

---

events.html

@jdebacker will present Cost-of-Capital-Calculator

Featured event -- November 30 demo day

---

Newsletter/archive.html
Newsletter/raw/Nov20_Newsletter.html

To add the Nov 2020 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on Wednesday, Nov 25. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Nov20_Newsletter.html

Nov 2020 newsletter draft

---

.github/workflows/update_catalog.yml

@hdoupe Schedule was changed to cron at 1 AM. Ready to merge.

Changed schedule to cron in catalog action

---

Community/contribute.html
Community/council.html
Community/council.md

This PR add's Nikhil to the Leadership Council as the maintainer of OpenFisca-UK.
cc @nikhilwoodruff

Add Nikhil to leadership council

---

Newsletter/archive.html
Newsletter/raw/Dec20_Newsletter.html

To add the **Dec 2020** PSL newsletter to the newsletter page. I'll plan to send the newsletter out on **Monday, Dec 28**. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Dec20_Newsletter.html

Dec 2020 newsletter draft

---

events.html

Updates the events page to feature the January 25 Demo Day on the scf and microdf packages by @MaxGhenis

Featured event - January 25 Demo Day

---

.github/workflows/update_community_docs.yml
environment.yml

This PR creates a new action which will update the community pages whenever the associated markdown file is updated. The `environment` file has been updated to include `pandoc`. Addresses #221.
@Peter-Metz @jdebacker

GH action to update community docs

---

Newsletter/archive.html
Newsletter/raw/Jan21_Newsletter.html

To add the Jan 2021 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on Monday, Jan 25. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Jan21_Newsletter.html

Jan 2021 newsletter draft

---

events.html

How to use the Compute Studio API to run and save policy simulations -- @MattHJensen

Update events page to feature February 8 Demo Day

---

events.html

@jdebacker will cover the basics of open source workflow and contributing to PSL projects

Featured Event: February 22 Demo Day

---

Newsletter/archive.html
Newsletter/raw/Feb21_Newsletter.html

To add the Feb 2021 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on Wednesday, Feb 24. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Feb21_Newsletter.html

Feb 2021 newsletter draft

---

Newsletter/archive.html

Add Mailchimp signup form to newsletter page

---

CSS/catalog.css
CSS/page.css
Catalog/index.html
Catalog/library_criteria.html
Community/contribute.html
Community/council.html
Community/initiatives.html
Community/roadmap.html
Newsletter/archive.html
Tools/Catalog-Builder/templates/catalog_template.html
Tools/Page-Builder/footer.html
Tools/Page-Builder/head.html
Tools/Page-Builder/make_pages.sh
about.html
events.html
index.html

Addresses #232. Screenshot of the About page below:

Add footer with social media links to pslmodels.org

---

events.html

March 8 at 11:30a from @hdoupe

Demo Day: Stacking tax policy changes with Compute Studio

---

events.html

@MaxGhenis will demo the Black code formatter

Post 3.22 Demo Day to Events Page

---

events.html

@jdebacker will show how to automate deployment of project documentation via Jupyter Book and GitHub Actions.
5/17 at 11:30a ET

Featured Event: Demo Day 5/17

---

Newsletter/archive.html

Attempted fix for this issue on the Newsletter page (bug does not appear locally):

Attempted fix for newsletter signup form overflow

---

events.html

@andersonfrailey will overview the Tax-Brain Python API and introduce new features

Demo Day - June 14

---

Catalog/library_criteria.md

Aesthetic changes to criteria.md

---

Catalog/catalog.json
Catalog/index.html
Newsletter/archive.html
Newsletter/raw/Jul21_Newsletter.html

To add the Jul 2021 PSL newsletter to the newsletter page. I'll plan to send the newsletter out on Friday, July 13. Feel free to suggest any edits or additions before then.
Newsletter Draft: https://htmlpreview.github.io/?https://github.com/towashington/PSL/blob/master/Newsletter/raw/Jul21_Newsletter.html

Jul 2021 newsletter draft

---

events.html

@rickecon will present on data visualization in Bokeh on August 23 at 11:30a ET

Update events page with August 23 demo day

---

events.html

@hdoupe will show how to deploy web apps on Compute Studio at Monday's (9/20) demo day

Demo Day September 20

---

events.html

The PolicyEngine calls should now appear on the PSL calendar

Update embed link for Google calendar

---

events.html

@MaxGhenis will present on data fusion with the `synthimpute` package

November 15 Demo Day

---

environment.yml

`pip` install `requests_mock` - again!

---

Catalog/register.json
Incubating/register.json

This PR updates the lists of projects in the incubating and cataloged registers.

Update catalog registers

---

.github/workflows/update_catalog.yml
CSS/catalog.css
Incubating/catalog.json
Incubating/register.json
Tools/Catalog-Builder/catalog_builder/catalog.py
Tools/Catalog-Builder/catalog_builder/tests/test_catalog.py
Tools/Catalog-Builder/catalog_builder/utils.py

This PR:
* Updates the image sizes used on the catalog cards to keep original dimensions
* Authenticates as a GitHub user for the GitHub API calls to prevent too many requests errors
* Update the GH actions to use a GH token to authenticate
* Fixes a typo in the `Incubating/register.json`

Image sizing

---

CSS/catalog.css
Tools/Catalog-Builder/catalog_builder/catalog.py

Modifications to `catalog_builder/catalog.py`:
- Error Handling in `load_catalog` Method: Introduced try-except blocks around the logic that fetches and parses `PSL_catalog.json` from project repositories. This update is designed to catch and log issues arising from missing or malformed `PSL_catalog.json` files, as well as handle unexpected errors during the API request process.
- Logging for Skipped Projects: Implemented logging warnings for cases where projects are skipped due to HTTP errors (e.g., rate limits or missing files) or JSON parsing errors (malformed JSON). An error log is also added for any other unexpected exceptions, ensuring that processing continues to the next project without halting the build.
Updates to `CSS/catalog.css`:
- Adjustments for User Logos: Modified the CSS …

Resolve Issues 303 and 313
