README.md
This PR fixes and activates links in the README to the standards, contributor guide, and roadmap.
=> Activate links readme

Core/Community/roadmap.md, Core/Criteria/library_criteria.md, Core/Tools/Catalog-Builder/README.md, Core/Tools/Standards-Tests/README.md, README.md, RELEASES.md
I was inspired by the the Linux Foundation's [Core Infrastructure Initiative](https://www.coreinfrastructure.org/programs/badge-program/) to replace our usage of "Standards" and "Guidelines" with "criteria."  
I will leave this up for a few days in case someone objects.
=> standards and guidelines -> criteria

Core/Criteria/library_criteria.md
Changes and motivations.
- Allow the CC0 license, which is not [actually OSI-approved.](https://opensource.org/faq#cc-zero). The motivation is that some likely PSL projects (like Tax-Calculator) are licensed CC0 and we like it. 
- Downgrade code test coverage reporting from a requirement to a suggestion, but upgrade the existence of unit testing to a requirement from nothing. The motivation is that code coverage is hard to calculate for some languages, like STATA. 
- Require a systematic versioning scheme, but only suggest semvar. The motivation is to be less dogmatic/opinionated.
=> Adjust PSL Criteria

Tools/Catalog-Builder/catalog_builder/utils.py
This PR modifies the catalog builder pre-parser to be more inclusive of different types of bullet points. These issues came to my attention when running the catalog builder on the B-Tax json file.
Namely, bullet points can be denoted by `* ` or `- ` in markdown and third-tier bullet points require an extra indent to be rendered as such.
@MattHJensen @martinholmer @andersonfrailey @hdoupe
=> Modify catalog builder pre-parser

Tools/Catalog-Builder/templates/model_template.html, Tools/Catalog-Builder/templates/models_template.html, Tools/Page-Builder/page_builder/pages.json, Tools/Page-Builder/page_builder/tests/TestFiles/testpage.html, Tools/Page-Builder/templates/page_template.html, Tools/Web/pages/about.html, Tools/Web/pages/catalog.html, Tools/Web/pages/news.html, Tools/Web/pages/projects/B-Tax.html, Tools/Web/pages/projects/OG-USA.html, index.html
This PR adds Google analytics to all of the web pages and updates the templates so that they will include the needed scripts in each of the HTML files that are produced using them.
@Peter-Metz @hdoupe @MattHJensen
=> Add Google Analytics

Community/contribute.md
After thinking on this further, I prefer a transparant, public, approach to model submissions, rather than requiring that private emails be sent to me. 
@hdoupe, could you suggest an addition to the new blurb about adding `PSL_catalog.json` to the applying project repo?
=> make model submission process transparent

Criteria/library_criteria.md, Tools/Catalog-Builder/README.md, Tools/Catalog-Builder/catalog_builder/catalog.py
I have a couple of questions:
- are we OK with calling the `PSL_catalog.json` a configuration file?
- if so, I'll swap the name in the docs from specifications file to configuration file to be consistent
- is the [section](https://github.com/open-source-economics/PSL/tree/master/Tools/Catalog-Builder#catalog-specification-file-psl_catalogjson) on the `PSL_catalog.json` file in the `Catalog-Builder/README.md` document the right place to link to?
Also, my text editor trimmed a bunch of spaces on the `library_criteria.md` document. I tried to isolate those to the first commit. The second commit contains only the changes that I made.
cc @MattHJensen @andersonfrailey
=> Adds PSL_catalog.json to the PSL criteria

README.md
This PR adds a link to the PSL chat room in the README file. As I [stated yesterday][1], @MattHJensen, @Peter-Metz, @andersonfrailey, and I have been using the PSL chat room for about a month and a half now. I've enjoyed having the option to communicate over chat, and I've enjoyed the free and open-source [Riot chat application][2]. I hope adding a link to the README makes it more apparent that chat is one of several ways that people can engage with the PSL community.
[1]: https://github.com/open-source-economics/PSL/issues/9#issuecomment-436753485
[2]: https://about.riot.im/
=> Add link to PSL chat room in the README

Catalog/Behavioral-Responses.html, Catalog/Tax-Calculator.html, Catalog/catalog.json, Catalog/index.html, README.md, Tools/Catalog-Builder/register.json, index.html
This PR adds the [Behavioral-Responses](https://github.com/open-source-economics/Behavioral-Responses) model to the PSL catalog and updates the Tax-Calculator catalog card.
Additionally, this PR fixes a typo in the PSL `README.md` (changes "transparancy" to "transparency")
cc: @martinholmer @MattHJensen @hdoupe @andersonfrailey
=> Add Behavioral-Responses model to and update PSL Catalog 

Community/contribute.md
This PR fixes a broken link to register.json. I am opening a separate issue for the discussion of where register.json should be located.
=> correct link to register.json

Tools/Catalog-Builder/README.md
This PR adds some instructions for opening the resulting HTML files on your computer.
@martinholmer do you have any feedback on this additional documentation? Is there anything that I should add or clarify?
=> Add instructions for previewing the HTML files

NEWS.md, Tools/Page-Builder/page_builder/pagebuilder.py, Tools/Page-Builder/page_builder/pages.json, Tools/Page-Builder/templates/index_template.html, about.html, index.html, news.html
This PR is in response to issue [#60](https://github.com/open-source-economics/PSL/issues/60)
Page-builder now pulls text from `NEWS.md` when it creates `index.html` so that `index.html` does not have to be manually updated each time there is a new news item. One caveat to the way things are currently structured: if someone wanted to make changes to the PSL homepage, they would have to make changes to `Tools/Page-Builder/templates/index_template.html` as opposed to `index.html` directly so that their changes are not overridden when `pagebuilder.py` is run.
Do you think this will pose a problem?
@MattHJensen @andersonfrailey @hdoupe
=> Update PSL homepage with text from NEWS.md

Tools/Catalog-Builder/catalog_builder/utils.py
@Peter-Metz pointed out that the catalog-builder response status code checking is a buggy. This PR swaps the order of the status code checks so that API limit errors (403 codes) will have a different error message than other non-ok (i.e. non 200) status codes.
=> Check status code is 403 _before_ checking if its 200

CSS/page.css, Tools/Page-Builder/templates/index_template.html, Tools/Page-Builder/templates/page_template.html, about.html, index.html, news.html
This PR replaces most the `style` elements we have built into the `index.html`, `about.html`, and `news.html` pages with a single CSS file. It doesn't alter the appearance of the websites at all, but it should make maintenance easier. I'll also want to replace the `style` elements in the individual model pages, but I figure waiting until we resolve issue #84 via PR #87 or some other PR will save a lot of potential confusion.
cc @hdoupe
=> Add CSS Files

CSS/page.css, Tools/Page-Builder/templates/index_template.html, index.html
This PR makes a handful of aesthetic updates to the PSL homepage. Highlights include:
1. Centers PSL logo, "Open Models == Better Policy", and Catalog button
2. Catalog button, About/Contribute/News cards turn blue when mouse hovers
3. "News" card is now an embedded tweet from @PSLModels. I couldn't find a good way to automate this, but embedding the latest tweet takes just a few seconds, and I'm happy to keep this up to date
4. Change order and widths of About/Contribute/News cards
5. Tweak some fonts and font sizes
The screenshot below is taken when my mouse is hovering over the Catalog button. There's a similar effect for the three cards as well
cc: @MattHJensen @hdoupe @andersonfrailey
=> Aesthetic updates to pslmodels.org homepage

CSS/catalog.css, CSS/page.css, Catalog/index.html, index.html
PR #93 messed up some of the CSS for the catalog page. This PR creates separate css files for the homepage and the catalog page to avoid that confusion in the future.
@hdoupe and I also tweak the hover highlighting on the homepage to a slightly less blue color.
cc: @MattHJensen @andersonfrailey
=> Fix Catalog page

.travis.yml, Tools/Catalog-Builder/README.md, Tools/Catalog-Builder/catalog_builder/catalog.py, Tools/Catalog-Builder/catalog_builder/tests/test_catalog.py, Tools/Catalog-Builder/catalog_builder/utils.py
This PR makes a series of updates to the catalog builder package:
- Throws an exception, `URLFormatError`,  if a user attempts to specify a URL as the "source" for a "github_file" type `PSL_catalog.json` attribute. "source" should be a filename.
- The `--build-one` keyword argument is added to the cli. This allows the user to run the catalog-builder for one project. This is helpful when someone is adding a project to the Catalog and is tweaking their `PSL_catalog.json` file and card/project page.
- Enables Travis CI for the catalog-builder tests.
- Re-formats the catalog builder README file.
=> Catalog builder updates

README.md
This PR adds the leadership council and a code of conduct to the readme. It should be merged *after* #107. 
Given that we did not discuss the code of conduct reporting standards explicitly in our recent council meeting, I ask that the leadership council please review this PR per our bylaws. Reviews and feedback from the rest of the community is also welcome. 
cc @martinholmer @jdebacker @rickecon @hdoupe
=> add leadership council & code of conduct to readme

Catalog/Tax-Brain.html, Catalog/catalog.json, Catalog/index.html, Tools/Catalog-Builder/register.json
This PR adds Tax-Brain to the PSL catalog. Tax-Brain integrates multiple open source tax models in one package. More information on the project can be found on its [GitHub page](https://github.com/PSLmodels/Tax-Brain).
cc @hdoupe @MattHJensen @Peter-Metz
=> Add Tax-Brain to PSL catalog

Criteria/library_criteria.md
Interoperability criteria 2-4 were not defined and not being used by PSL-Infrastructure. This PR removes them. 
If PSL-Infrastructure provides technology in the future that would benefit from similar criteria, such as centralized project websites or documentation sites, then we can add the helpful criteria at that point. 
Given that the criteria were not defined, I am not going to set up a formal meeting of the PSL leadership council to approve these changes, but I will leave the PR open for at least 24 hours for comments. 
Also, resolves #14.
=> Remove 2-4 interoperability criteria

Catalog/catalog.json, Catalog/index.html, Catalog/register.json
This PR adds [Tax-Cruncher](https://github.com/PSLmodels/Tax-Cruncher) to the catalog builder's `register.json`, thereby adding it to the PSL Catalog.
=> Add Tax-Cruncher to the PSL Catalog

Community/council.md
Adding Weifeng to the PSL Leadership Council after the admittance of PCI-China to the PSL catalog. 
We have an online leadership council meeting every other Tuesday where we take care of any official business. Council members try to make it when they can, but we can't all always attend. The meeting is open to anyone who wants to attend, but only council members can participate in votes. We also have general community discussions on the alternating Tuesdays. Call in info at https://www.pslmodels.org/events. 
Thanks again to @towashington (Weifeng) and @ctszkin (Julian) for cataloging your project with PSL and to @Peter-Metz for spearheading the council's review.
=> Add Weifeng to council

Community/council.md
This specifies that @towashington's role on the council is to represent the PCI-China project rather than the PCI umbrella brand.
=> WZ PSL-lc project -> PCI-China

Catalog/index.html, Newsletter/archive.html, about.html, events.html, index.html
This PR adds a donate link to the top of the webpages on the PSLmodels.org site.  The link takes users to PSL's Open Collective page, where tax-deductible contributions can be made to support PSL.
=> Add donate link to top of pages

Tools/Catalog-Builder/catalog_builder/catalog.py
Python's built-in `sorted()` function sorts upper-case words ahead of lower-case words (e.g. `Tax-Cruncher` ahead of `microdf`). This seems undesirable to me.
The rest of the changes are from the `black` Python code formatter.
=> Case-agnostic sorting for PSL catalog

events.html
Updates the featured event to display the first PSL demo day on November 2
https://htmlpreview.github.io/?https://github.com/Peter-Metz/PSL-Core/blob/featured/events.html
=> PSL demo day -- featured event

.github/workflows/update_catalog.yml
@hdoupe I realized that the catalog builder action will fail if empty commits are not allowed (no changes are made to the catalog), so I've added `--allow-empty` to the commit flags.
Also:
- The miniconda setup action has been bumped to 2.0.1
- The pull-upstream-changes action has been removed (don't need to pull from upstream if you're operating on master)
- The "Get current date" step has been removed (it's unused)
=> Minor amendments to catalog builder action

Catalog/register.json
See https://github.com/nikhilwoodruff/openfisca-uk/issues/22 for the checklist of PSL criteria - all MUST criteria have been met except for the moving of the repository into the PSLmodels organisation. Let me know if there's any other procedure to follow here.
=> Add OpenFisca-UK to PSL Catalog register.json

Newsletter/archive.html, Tools/Catalog-Builder/templates/catalog_template.html, Tools/Page-Builder/head.html, about.html, events.html, index.html
Adds `twitter:title` tag to each page. I think this is [required](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary) for the card to render
=> Attempted fix for Twitter cards

Catalog/register.json
This PR adds taxdata to the PSL models register. The catalog listing is [here](https://github.com/PSLmodels/taxdata/blob/master/PSL_catalog.json). Let me know if there's anything else I need to add in.
=> Add taxdata to register

Community/contribute.html, Community/contribute.md
This PR addresses Issue #219 by replacing the PSL office hours with a link to the calendar of events where potential contributors can find information on joining the various PSL calls held on a regular basis.
=> Update office hours on contribute page

Tools/Page-Builder/make_pages.sh
This PR fixes the problem of introducing breaking changes to the CSS of HTML pages when running the page builder GH action (#240 and #210). The solution is to make sure that the builder shell script `make_pages.sh` links each `pandoc` command to the `page.css` CSS style.
cc @Peter-Metz
=> Fix page builder GH action

Catalog/register.json, Tools/Catalog-Builder/catalog_builder/utils.py
This PR adds the [NYFRB DSGE model](https://github.com/FRBNY-DSGE/DSGE.jl) to the PSL Catalog.
The update will be reflected on pslmodels.org when the catalog builder GH action is triggered tonight.
cc @jdebacker
=> Add NY Fed DSGE model to PSL Catalog

Community/council.md
This PR adds Daniel Bunn to the list of PSL Leadership Council members, representing the `capital-cost-recovery` project.
=> Update with new council member

Catalog/register.json, Tools/Catalog-Builder/catalog_builder/utils.py
Adds `capital-cost-recovery` to the PSL register. A GH action will add it to the catalog tonight.
In addition, this PR makes the previously required fields of PSL_catalog.json optional.
=> Add capital-cost-recovery project to PSL catalog

events.html
The next Demo Day will feature @nikhilwoodruff on PolicyEngine UK. Wednesday, September 8 at 12p ET.
=> Update events page and featured demo day

.github/workflows/update_catalog.yml
This PR updates the `update_catalog` action to also build the catalog on a push to master (not just daily).
=> Build catalog on push to master

Tools/Catalog-Builder/catalog_builder/utils.py
This PR fixed an HTTP error where the the GitHub API is not responsive. From [this Stack Overflow thread](https://stackoverflow.com/questions/39907742/github-api-is-responding-with-a-403-when-using-requests-request-function) it appears that using a header in the request is important to avoid this issue.  The changes here implement that and seem to work when I execute the `catalog.py` script locally.
=> Fix http error

Tools/Catalog-Builder/catalog_builder/utils.py
This PR adds a sleep command to the GitHub API request since PR #293 didn't seem to solve the issue of the 403 code in the response.
=> Add sleep in API request

environment.yml
The package wasn't available on `conda`.
=> `pip` install `requests_mock`

Catalog/register.json
This PR adds the OG-Core model to the PSL Catalogue list `register.json`. OG-Core was originally OG-USA, which was subsequently split into two pieces (OG-Core and OG-USA). Because OG-Core has different functionality and documentation that is valuable and separate from the country calibrations, OG-Core should probably be in the catalogue list.
cc: @jdebacker
=> Added OG-Core to register.json

Incubating/register.json
This PR updates the `/Incubating/register.json` file to comment out incubating projects that do not have a `PSL_catalog.json` file in the hopes that this allows the catalog builder to run through.
=> Comment out incubating projects
